#!/bin/bash

# config:
your_binary_file="/home/rafalcode/work/antinet/doc_and_drafts/net_trivial_tests/tunproxy.bin"

while true ; do 
	setcap "cap_net_admin+eip cap_net_raw+eip" "${your_binary_file}"
	# setcap "cap_net_admin+eip cap_net_raw+eip" "${your_binary_file}" # <--- raw not needed for now, untill we would do own eth frames and so on
	# ip a add "${your_ip_ipgalaxy}/8" dev toto0 # <---- your IP here - no longer used, now the program can configure it itself
	# ip link set toto0 up # <--- program does it now itself
	sleep 0.1 ; 
done

