#!/bin/bash -e

echo ; echo ; echo "Installing the scripts/tools needed to run/develop Galaxy42 network..."

if [[ $EUID -ne 0 ]]; then
	echo "ERROR: This script must be run as root. Log in as root user, then run this script." 1>&2
	echo
	exit 1
fi

pwd=$(PWD)

cd netpriv_scripts  
./install
cd $pwd

cd setcap_scripts
./install
cd $pwd


echo "OK - all seems installed" ; echo
