# For creating tun
sudo: required

# Enable C++ support
language: cpp
    
os: 
  - linux
  - osx

dist: trusty
osx_image: xcode7.3


# Adding setcap for tunserver.elf etc.
before_script:
  - cd share/script/install-as-root/ && sudo ./install -y

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi

env:
  global:
    - COVERAGE=0
    - EXTLEVEL=0
  matrix:
    - EXTLEVEL=30
    - EXTLEVEL=20
    - EXTLEVEL=10

matrix:
    fast_finish: true

    include:
      - os: linux
        env: COVERAGE=1 EXTLEVEL=0
        dist: trusty
        compiler: gcc
        addons:
          apt:
            sources:
              - ubuntu-toolchain-r-test
            packages:
              - gcc-5
              - g++-5
              - libboost-all-dev
              - libfftw3-dev
        before_install:
          - sudo add-apt-repository ppa:chris-lea/libsodium -y
          - sudo apt-get update -q && sudo apt-get install libsodium-dev -y;
          - pip install --user cpp-coveralls


      - os: osx
        env: COVERAGE=0 EXTLEVEL=0
        compiler: clang
        before_install:
          - brew update
          - brew install autoconf
          - brew install pkg-config
          - brew install cmake
          - brew install libsodium
          - brew install boost

    allow_failures:
      - os: osx
      - env: EXTLEVEL=30
      - env: EXTLEVEL=20
      - env: EXTLEVEL=10


script:
  - cd ${TRAVIS_BUILD_DIR} # back to main dir 
  - ./do --go

after_success:
  - ./test-release.elf    # run gtests
  - if[ "$COVERAGE" = "1" ]; then coveralls -e src/test -e build_extra -e depends --gcov-options '\-lp' --gcov 'gcov-5'

#notifications:
#  irc:
#    on_success: change
#    on_failure: change
#    channels:
#      - "icann.irc.meshnet.pl#antinet-dev"
#    template:
#      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
#      - "Change view : %{compare_url}"
#      - "Build details : %{build_url}"
  #email:
  #  to minimize spam
  #  on_success: change
  #  on_failure: always
  #recipients:
  #  - one@example.com
  #  - other@example.com


