# For creating tun
sudo: required

# Ubuntu 14.04 Trusty support
dist: trusty

# Enable C++ support
language: cpp

addons:
    apt:
        sources:
        # add PPAs with more up-to-date toolchains
            - ubuntu-toolchain-r-test
        packages:
        # install toolchains
        - gcc-5
        - g++-5
        - libboost-all-dev
        - libfftw3-dev

# Adding setcap for tunserver.elf etc.
before_script:
    - cd share/script/install-as-root/ && sudo ./install -y

# Adding ppa for and install libsodium
before_install:
    - sudo add-apt-repository ppa:chris-lea/libsodium -y
    - sudo apt-get update -q && sudo apt-get install libsodium-dev -y;

# Set g++-5 and gcc-5 for c++14 support
install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi

# Compiler selection
compiler:
    - gcc

# Build steps
script: 
    - pwd
    - cd ../../../   # back to main dir
    - ./do

notifications:
    irc:
        channels:
            - "icann.irc.meshnet.pl#antinet-dev"
        #    on_success: [always|never|change] # default: always
        #    on_failure: [always|never|change] # default: always
        template:
            - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
            - "Change view : %{compare_url}"
            - "Build details : %{build_url}"

