#!/bin/bash
while true ; do clear ;
	echo ; echo ; echo ;
	./rundevel.sh ; echo ;
	echo ; echo ; echo ;
	echo ; echo ; echo ;
	echo ; echo ; echo ;
	echo ; echo ; echo ;
	echo ; echo ; echo ;
	sleep 1 ;
done

