#!/bin/bash
readonly myname=$(basename "$BASH_SOURCE")
function myprint { printf "[Script %s]: %s \n" "$myname" "$*" ; }

program_for_flags="./tunserver.elf"
program_to_run="./tunserver.elf"
myprint "Running program ($program_to_run) with SAFE THREADS, and SAFE MISC UB (INCLUDING OVERFLOWS) OPTIONS"

${program_for_flags} --print-flags-flavour > /dev/null || { myprint "Can not run program to test flags ($program_for_flags)."; }

checks_enabled=0 # count checks we will enable
checks_existing=0 # count how many checks we could have run

((checks_existing++))
${program_for_flags} --print-flags-flavour | grep "FLAVOUR_TSAN_FULL" && {
	((checks_enabled++))
	sudo TSAN_OPTIONS="halt_on_error=1"
	myprint "Ok, we will HALT on TSAN errors"
	cat << EOF
 _____ ____    _    _   _
|_   _/ ___|  / \\  | \\ | |
  | | \\___ \\ / _ \\ |  \\| |
  | |  ___) / ___ \\| |\\  |
  |_| |____/_/   \\_\\_| \\_|

EOF
} || { myprint "Warning: will not halt on TSAN errors" }

((checks_existing++))
${program_for_flags} --print-flags-flavour | grep "FLAVOUR_UBSAN_FULL" && {
	((checks_enabled++))
	sudo UBSAN_OPTIONS="halt_on_error=1"
	myprint "Ok, we will HALT on UBSAN errors"
	cat << EOF
	 _   _ ____ ____    _    _   _
	 | | | | __ ) ___|  / \\  | \\ | |
	 | | | |  _ \\___ \\ / _ \\ |  \\| |
	 | |_| | |_) |__) / ___ \\| |\\  |
	  \\___/|____/____/_/   \\_\\_| \\_|

EOF
} || { myprint "Warning: will not halt on UBSAN errors" }

(( checks_enabled == )) && { myprint "Error: can not run any checks, exiting" ; exit 1 ; }
(( checks_enabled < checks_existing )) && { myprint "Warning: only some checks are enabled ($checks_enabled/$checks_existing)" ; }

set -x
./nocap-tunserver.elf "$@"
program_return=$$

echo "Exited."
(( checks_enabled < checks_existing )) && { myprint "Warning: only some checks are enabled ($checks_enabled/$checks_existing)" ; }

exit $program_return
