#!/bin/bash -e
# *** review *** this program was reviewed and not have critical flaws

# Usage: just run it. Or run it with option '-y' to skip the confirmation (batch process, tests travis etc)

echo ; echo ; echo "Installing the scripts/tools needed to run/develop (some parts of) Galaxy42/Antinet network..."

if [[ $EUID -ne 0 ]]; then
	echo
	echo "ERROR: This script must be run as root. Log in as root user, then run this script." 1>&2
	echo
	exit 1
fi

pwd="$PWD"

echo "--------------------------------------------------------------------"
cd netpriv_scripts
./install "$1"
cd "$pwd"

echo "--------------------------------------------------------------------"
cd setcap_scripts
./install "$1"
cd "$pwd"


echo "OK - all seems installed ... but MAKE SURE you followed any extra instructions above, including running (as root) visudo and configuring that." ; echo
