#!/bin/bash

function usage() {
	printf "

	Run this program with options:

	-t Trims from .po files obsolite strings that are no longer present in sources.
	-u Updates the .po and .mo files by adding new strings that were since last time added in sources.

	(Need manual commands to create first empty pot file maybe)

"

}

printf "

This script is for translators (of human languages) and for developers creating translations.
Use -h for help.

"

textdomain='galaxy42_installer'
sourcefile="install.sh"

MYTMP="vartmp/lang/" # <-- must be safe local dir! (we will delete it!)
rm -rf "$MYTMP"
mkdir -p "$MYTMP"

function lang_new_and_translate() {

	xgettext -j --no-location   -o "src-misc/locale/${textdomain}/messages.pot"  "${sourcefile}"
	# -j
	for lang in pl en
	do
		msgmerge --update "src-misc/locale/${textdomain}/${lang}.po"   "src-misc/locale/${textdomain}/messages.pot" || exit
		$EDITOR "src-misc/locale/${textdomain}/${lang}.po"
		msgfmt --check --endianness=little "src-misc/locale/${textdomain}/${lang}.po" -o "./share/locale/${lang}/LC_MESSAGES/${textdomain}.mo" || exit
	done

}

function trim_obsolete {
	echo "Removing obsolete strings that are no longer in sourcefile=$sourcefile"

	# set -x # debug
	xgettext  -o "$MYTMP/fresh.pot"  "${sourcefile}"

	for lang in pl en
	do
		pofile="src-misc/locale/${textdomain}/${lang}.po"
		pofile_clean="${pofile}-clean"
		pofile_clean2="${pofile}-clean2"
		msgattrib --set-obsolete --ignore-file="$MYTMP/fresh.pot" -o "$pofile_clean" "$pofile" || exit
		msgattrib --no-obsolete -o "$pofile_clean2" "$pofile_clean" || exit
		echo "Diff of trimming:"
		pager="tee"
		if hash "colordiff" 2>/dev/null ; then pager="colordiff" ; fi
		diff -Nuar "$pofile" "$pofile_clean2" | $pager
		mv "$pofile_clean2" "$pofile"
		rm "$pofile_clean"
	done
}

while getopts ":tuh" opt; do
	  case $opt in
	  	t)
				trim_obsolete
				;;
	  	u)
				lang_new_and_translate
				;;
			h)
				usage
				;;
			'?')
				echo "Unknown option."
				usage
				exit 1
				;;
	  esac
done







