#!/bin/bash -e
# *** review *** this program was reviewed and does not have critical flaws

echo "This will install some of our util programs (system-wide)"
echo "This programs are not yet fully secured, likely can contain some exploits especially exploitable by local malicious user" # TODO XXX
echo "(Please review the code before running it!)"
echo "Type OK (in upper case) to install it anyway, or any other key or ctrl-c to exit now"

read ok ; [[ "$ok" == "OK" ]] || { echo "Aborting" ; exit 1 ; } # !
echo "Installing... "

cp bin/netpriv1 /usr/local/bin/
cp bin/netpriv2 /usr/local/bin/
cp bin/netpriv9 /usr/local/bin/
cp bin/netpriv_enter /usr/local/bin/
# possible race condition here betwen copy and chmod, but doesn't matter, because
# this script should be run in safe location, and /usr/bin also is one (controlled just by root)
chmod u=wrx,g=rx,o=rx /usr/local/bin/netpriv1
chmod u=wrx,g=rx,o=rx /usr/local/bin/netpriv2
chmod u=wrx,g=rx,o=rx /usr/local/bin/netpriv9
chmod u=wrx,g=rx,o=rx /usr/local/bin/netpriv_enter

echo
echo "--- DO THIS ---"
echo "Ok, now you should probably edit sudoers (e.g. as root with command: visudo)"
echo "And there in editor add line like:"
echo "alice ALL=(ALL)NOPASSWD:/usr/local/bin/netpriv1"
echo "alice ALL=(ALL)NOPASSWD:/usr/local/bin/netpriv2"
echo "alice ALL=(ALL)NOPASSWD:/usr/local/bin/netpriv9"
echo "alice ALL=(ALL)NOPASSWD:/usr/local/bin/netpriv_enter"
echo ""
echo "Where 'alice' should be the name of user (or group etc) that is allowed to set his programs to have netadmin capability"
echo "Consider the security implications: the user that you will allow, will be able to configure the network interfaces on such computer as admin"
echo

echo "... after reading above instructions, press ENTER to continue"
read _
echo

